services:

  app:
    restart: on-failure
    container_name: demented_devel_app
    build:
      context: .
      dockerfile: ./devel.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9001:9001"

  postgres:
    restart: on-failure
    container_name: demented_devel_db
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres-data:/postgresql_data
      - ./docker/regtest/pg/data/pg/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_ADDITIONAL_DATABASES: regtest_nostr_relay0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /postgresql_data
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=postgres --username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
